version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt

sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub
